/** Demo questions. Every distractor carries a tag from DEMO_VOCABULARY. */

export interface SeedQuestion {
  id: string;
  topicId: string;
  stem: string;
  page: number;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  correct: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  options: { label: 'A' | 'B' | 'C' | 'D'; text: string; tag: string | null }[];
}

const AVC = 'assignment_vs_comparison';
const SLE = 'strict_vs_loose_equality';
const PREC = 'operator_precedence';
const TRUTHY = 'truthy_falsy';
const SCOPE = 'scope_confusion';

export const DEMO_QUESTIONS: SeedQuestion[] = [
  // ── Variables ──────────────────────────────────────────────────────────────
  {
    id: 'q_variables_1',
    topicId: 'topic_variables',
    stem: 'Which keyword should you use for a value that must never be reassigned?',
    page: 3,
    difficulty: 'beginner',
    correct: 'A',
    explanation: 'const prevents reassignment; assigning to a const throws an error (p.3).',
    options: [
      { label: 'A', text: 'const', tag: null },
      { label: 'B', text: 'let', tag: SCOPE },
      { label: 'C', text: 'var', tag: SCOPE },
      { label: 'D', text: 'fixed', tag: TRUTHY },
    ],
  },
  {
    id: 'q_variables_2',
    topicId: 'topic_variables',
    stem: 'What does `let score = 10;` do?',
    page: 1,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'A single = stores the value 10 under the name score (p.1).',
    options: [
      { label: 'A', text: 'Checks whether score is equal to 10', tag: AVC },
      { label: 'B', text: 'Stores the value 10 in a variable named score', tag: null },
      { label: 'C', text: 'Compares score with 10 and returns true or false', tag: AVC },
      { label: 'D', text: 'Creates a constant that cannot change', tag: SCOPE },
    ],
  },
  {
    id: 'q_variables_3',
    topicId: 'topic_variables',
    stem: 'Which variable name is NOT valid in JavaScript?',
    page: 4,
    difficulty: 'beginner',
    correct: 'C',
    explanation: 'A variable name cannot begin with a digit (p.4).',
    options: [
      { label: 'A', text: 'total_marks', tag: SCOPE },
      { label: 'B', text: '$price', tag: TRUTHY },
      { label: 'C', text: '2ndAttempt', tag: null },
      { label: 'D', text: 'studentAge', tag: SCOPE },
    ],
  },
  {
    id: 'q_variables_4',
    topicId: 'topic_variables',
    stem: 'Are `score` and `Score` the same variable?',
    page: 4,
    difficulty: 'beginner',
    correct: 'D',
    explanation: 'Variable names are case sensitive, so these are two different variables (p.4).',
    options: [
      { label: 'A', text: 'Yes, JavaScript ignores capital letters', tag: SLE },
      { label: 'B', text: 'Yes, but only inside a function', tag: SCOPE },
      { label: 'C', text: 'Only if both are declared with const', tag: PREC },
      { label: 'D', text: 'No, they are two different variables', tag: null },
    ],
  },
  {
    id: 'q_variables_5',
    topicId: 'topic_variables',
    stem: 'Why does modern JavaScript prefer `let` and `const` over `var`?',
    page: 5,
    difficulty: 'intermediate',
    correct: 'A',
    explanation:
      'A var declaration is visible throughout its whole function, even before its line, which causes confusion (p.5).',
    options: [
      { label: 'A', text: 'var is visible through the whole function, which is confusing', tag: null },
      { label: 'B', text: 'var cannot store numbers', tag: TRUTHY },
      { label: 'C', text: 'var compares values instead of assigning them', tag: AVC },
      { label: 'D', text: 'var only works inside loops', tag: SCOPE },
    ],
  },
  {
    id: 'q_variables_6',
    topicId: 'topic_variables',
    stem: 'How many times do you write `let` for the same variable?',
    page: 2,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'You write let once, when the variable is first created (p.2).',
    options: [
      { label: 'A', text: 'Every time you change its value', tag: SCOPE },
      { label: 'B', text: 'Once, when the variable is first created', tag: null },
      { label: 'C', text: 'Once per function that uses it', tag: SCOPE },
      { label: 'D', text: 'Only when comparing it to another value', tag: AVC },
    ],
  },

  // ── Conditionals ───────────────────────────────────────────────────────────
  {
    id: 'q_conditionals_1',
    topicId: 'topic_conditionals',
    stem: 'What is wrong with `if (score = 50) { ... }`?',
    page: 17,
    difficulty: 'beginner',
    correct: 'C',
    explanation:
      'A single = assigns. It stores 50 into score instead of asking whether score is 50. Use === (p.17).',
    options: [
      { label: 'A', text: 'Nothing — this correctly checks whether score is 50', tag: AVC },
      { label: 'B', text: 'The brackets are in the wrong place', tag: PREC },
      { label: 'C', text: 'It assigns 50 to score instead of comparing', tag: null },
      { label: 'D', text: 'score must be declared with const first', tag: SCOPE },
    ],
  },
  {
    id: 'q_conditionals_2',
    topicId: 'topic_conditionals',
    stem: 'Which operator asks whether two values are the same, without converting types?',
    page: 18,
    difficulty: 'beginner',
    correct: 'B',
    explanation: '=== is strict equality: it requires the same type as well as the same value (p.18).',
    options: [
      { label: 'A', text: '=', tag: AVC },
      { label: 'B', text: '===', tag: null },
      { label: 'C', text: '==', tag: SLE },
      { label: 'D', text: '=>', tag: PREC },
    ],
  },
  {
    id: 'q_conditionals_3',
    topicId: 'topic_conditionals',
    stem: "What does `'5' === 5` evaluate to?",
    page: 18,
    difficulty: 'intermediate',
    correct: 'D',
    explanation: 'Strict equality does not convert types, and a string is not a number (p.18).',
    options: [
      { label: 'A', text: 'true, because both represent five', tag: SLE },
      { label: 'B', text: 'It stores 5 into the string', tag: AVC },
      { label: 'C', text: 'It causes an error', tag: PREC },
      { label: 'D', text: 'false, because a string is not a number', tag: null },
    ],
  },
  {
    id: 'q_conditionals_4',
    topicId: 'topic_conditionals',
    stem: 'You want to run code only when `grade` holds the value "A". Which condition is correct?',
    page: 17,
    difficulty: 'beginner',
    correct: 'A',
    explanation: 'Use === to compare. A single = would assign "A" to grade (p.17).',
    options: [
      { label: 'A', text: "if (grade === 'A')", tag: null },
      { label: 'B', text: "if (grade = 'A')", tag: AVC },
      { label: 'C', text: "if (grade => 'A')", tag: PREC },
      { label: 'D', text: "if (grade := 'A')", tag: AVC },
    ],
  },
  {
    id: 'q_conditionals_5',
    topicId: 'topic_conditionals',
    stem: 'In an if / else if / else chain, how many branches run?',
    page: 19,
    difficulty: 'beginner',
    correct: 'C',
    explanation: 'Only the first matching branch runs (p.19).',
    options: [
      { label: 'A', text: 'Every branch whose condition is true', tag: TRUTHY },
      { label: 'B', text: 'All of them, in order', tag: PREC },
      { label: 'C', text: 'Only the first branch that matches', tag: null },
      { label: 'D', text: 'None, unless else is present', tag: TRUTHY },
    ],
  },
  {
    id: 'q_conditionals_6',
    topicId: 'topic_conditionals',
    stem: 'Which of these values is treated as false in a condition?',
    page: 20,
    difficulty: 'intermediate',
    correct: 'B',
    explanation:
      'The falsy values are 0, the empty string, null, undefined and NaN. "0" and [] are truthy (p.20).',
    options: [
      { label: 'A', text: "the string '0'", tag: TRUTHY },
      { label: 'B', text: 'the number 0', tag: null },
      { label: 'C', text: 'an empty array []', tag: TRUTHY },
      { label: 'D', text: 'the string "false"', tag: SLE },
    ],
  },

  // ── Functions ──────────────────────────────────────────────────────────────
  {
    id: 'q_functions_1',
    topicId: 'topic_functions',
    stem: 'What does the `return` keyword do?',
    page: 29,
    difficulty: 'beginner',
    correct: 'A',
    explanation: 'return sends a value back to whoever called the function (p.29).',
    options: [
      { label: 'A', text: 'Sends a value back to the caller', tag: null },
      { label: 'B', text: 'Prints a value to the console', tag: TRUTHY },
      { label: 'C', text: 'Restarts the function from the top', tag: PREC },
      { label: 'D', text: 'Stores the value in a global variable', tag: SCOPE },
    ],
  },
  {
    id: 'q_functions_2',
    topicId: 'topic_functions',
    stem: 'A variable declared with `let` inside a function can be used where?',
    page: 30,
    difficulty: 'intermediate',
    correct: 'C',
    explanation: 'It exists only inside that function; code outside cannot see it (p.30).',
    options: [
      { label: 'A', text: 'Anywhere in the file', tag: SCOPE },
      { label: 'B', text: 'Anywhere after the function is declared', tag: SCOPE },
      { label: 'C', text: 'Only inside that function', tag: null },
      { label: 'D', text: 'Only inside loops within that function', tag: PREC },
    ],
  },
  {
    id: 'q_functions_3',
    topicId: 'topic_functions',
    stem: 'In `function greet(name) { ... }`, what is `name`?',
    page: 28,
    difficulty: 'beginner',
    correct: 'D',
    explanation:
      'A parameter is the name in the declaration; the value passed at the call is the argument (p.28).',
    options: [
      { label: 'A', text: 'An argument', tag: SCOPE },
      { label: 'B', text: 'A global variable', tag: SCOPE },
      { label: 'C', text: 'A comparison', tag: AVC },
      { label: 'D', text: 'A parameter', tag: null },
    ],
  },
  {
    id: 'q_functions_4',
    topicId: 'topic_functions',
    stem: 'What does `double(4)` give, if `function double(n) { return n * 2; }`?',
    page: 29,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'The function returns n * 2, so 4 * 2 is 8 (p.29).',
    options: [
      { label: 'A', text: '4', tag: PREC },
      { label: 'B', text: '8', tag: null },
      { label: 'C', text: 'undefined', tag: TRUTHY },
      { label: 'D', text: 'It causes an error', tag: SCOPE },
    ],
  },
  {
    id: 'q_functions_5',
    topicId: 'topic_functions',
    stem: 'What happens to code written after a `return` statement?',
    page: 29,
    difficulty: 'intermediate',
    correct: 'A',
    explanation: 'Code after a return never runs (p.29).',
    options: [
      { label: 'A', text: 'It never runs', tag: null },
      { label: 'B', text: 'It runs before the return', tag: PREC },
      { label: 'C', text: 'It runs only if the return value is false', tag: TRUTHY },
      { label: 'D', text: 'It runs in the calling function instead', tag: SCOPE },
    ],
  },
  {
    id: 'q_functions_6',
    topicId: 'topic_functions',
    stem: 'What does the arrow function `const double = (n) => n * 2;` return?',
    page: 31,
    difficulty: 'intermediate',
    correct: 'C',
    explanation:
      'When the body is a single expression, its value is returned automatically (p.31).',
    options: [
      { label: 'A', text: 'Nothing, it needs an explicit return', tag: TRUTHY },
      { label: 'B', text: 'The value of n', tag: PREC },
      { label: 'C', text: 'n multiplied by 2', tag: null },
      { label: 'D', text: 'A new variable called double', tag: SCOPE },
    ],
  },

  // ── Remaining topics: enough to build a practice set without an LLM ────────
  {
    id: 'q_data_types_1',
    topicId: 'topic_data_types',
    stem: 'What does `typeof 7` give?',
    page: 10,
    difficulty: 'beginner',
    correct: 'A',
    explanation: 'typeof reports the type as a string; for 7 that is "number" (p.10).',
    options: [
      { label: 'A', text: '"number"', tag: null },
      { label: 'B', text: '"integer"', tag: SLE },
      { label: 'C', text: '7', tag: TRUTHY },
      { label: 'D', text: '"string"', tag: SLE },
    ],
  },
  {
    id: 'q_data_types_2',
    topicId: 'topic_data_types',
    stem: 'What is the difference between `null` and `undefined`?',
    page: 9,
    difficulty: 'intermediate',
    correct: 'B',
    explanation:
      'undefined means never given a value; null means deliberately given "no value" (p.9).',
    options: [
      { label: 'A', text: 'They are identical', tag: SLE },
      { label: 'B', text: 'undefined was never set; null was set to "no value"', tag: null },
      { label: 'C', text: 'null is zero and undefined is an empty string', tag: TRUTHY },
      { label: 'D', text: 'null only appears inside functions', tag: SCOPE },
    ],
  },
  {
    id: 'q_data_types_3',
    topicId: 'topic_data_types',
    stem: 'Which of these is a boolean?',
    page: 8,
    difficulty: 'beginner',
    correct: 'D',
    explanation: 'A boolean is either true or false (p.8).',
    options: [
      { label: 'A', text: "'true'", tag: SLE },
      { label: 'B', text: '1', tag: TRUTHY },
      { label: 'C', text: 'null', tag: TRUTHY },
      { label: 'D', text: 'false', tag: null },
    ],
  },
  {
    id: 'q_operators_1',
    topicId: 'topic_operators',
    stem: 'What does `2 + 3 * 4` evaluate to?',
    page: 13,
    difficulty: 'beginner',
    correct: 'C',
    explanation: 'Multiplication is applied before addition, so 3 * 4 is evaluated first (p.13).',
    options: [
      { label: 'A', text: '20', tag: PREC },
      { label: 'B', text: '24', tag: PREC },
      { label: 'C', text: '14', tag: null },
      { label: 'D', text: '9', tag: PREC },
    ],
  },
  {
    id: 'q_operators_2',
    topicId: 'topic_operators',
    stem: 'What does `10 % 3` give?',
    page: 11,
    difficulty: 'beginner',
    correct: 'A',
    explanation: '% is the remainder: 3 goes into 10 three times with 1 left over (p.11).',
    options: [
      { label: 'A', text: '1', tag: null },
      { label: 'B', text: '3', tag: PREC },
      { label: 'C', text: '3.33', tag: PREC },
      { label: 'D', text: '0', tag: TRUTHY },
    ],
  },
  {
    id: 'q_operators_3',
    topicId: 'topic_operators',
    stem: 'What does `total += 5` mean?',
    page: 14,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'The shorthand += combines addition with assignment (p.14).',
    options: [
      { label: 'A', text: 'Checks whether total equals 5', tag: AVC },
      { label: 'B', text: 'total = total + 5', tag: null },
      { label: 'C', text: 'total = 5', tag: AVC },
      { label: 'D', text: 'Adds 5 only if total is already true', tag: TRUTHY },
    ],
  },
  {
    id: 'q_loops_1',
    topicId: 'topic_loops',
    stem: 'How many times does `for (let i = 0; i < 5; i++)` repeat?',
    page: 22,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'It runs while i is less than 5, starting at 0 — five passes (p.22).',
    options: [
      { label: 'A', text: '4', tag: PREC },
      { label: 'B', text: '5', tag: null },
      { label: 'C', text: '6', tag: PREC },
      { label: 'D', text: 'Forever', tag: TRUTHY },
    ],
  },
  {
    id: 'q_loops_2',
    topicId: 'topic_loops',
    stem: 'What does `break` do inside a loop?',
    page: 25,
    difficulty: 'beginner',
    correct: 'C',
    explanation: 'break leaves the loop immediately (p.25).',
    options: [
      { label: 'A', text: 'Skips to the next pass', tag: PREC },
      { label: 'B', text: 'Restarts the loop', tag: PREC },
      { label: 'C', text: 'Leaves the loop immediately', tag: null },
      { label: 'D', text: 'Pauses until the condition is true', tag: TRUTHY },
    ],
  },
  {
    id: 'q_loops_3',
    topicId: 'topic_loops',
    stem: 'Why must something inside a `while` loop change the condition?',
    page: 24,
    difficulty: 'intermediate',
    correct: 'A',
    explanation: 'Otherwise the condition stays true and the loop never ends (p.24).',
    options: [
      { label: 'A', text: 'Otherwise the loop never ends', tag: null },
      { label: 'B', text: 'Otherwise it runs exactly once', tag: TRUTHY },
      { label: 'C', text: 'Otherwise the variable leaves scope', tag: SCOPE },
      { label: 'D', text: 'Otherwise the operators are applied backwards', tag: PREC },
    ],
  },
  {
    id: 'q_arrays_1',
    topicId: 'topic_arrays',
    stem: 'For `let marks = [70, 85, 92];`, what does `marks[1]` give?',
    page: 34,
    difficulty: 'beginner',
    correct: 'B',
    explanation: 'Indexes start at 0, so position 1 is the second item (p.34).',
    options: [
      { label: 'A', text: '70', tag: PREC },
      { label: 'B', text: '85', tag: null },
      { label: 'C', text: '92', tag: PREC },
      { label: 'D', text: 'undefined', tag: TRUTHY },
    ],
  },
  {
    id: 'q_arrays_2',
    topicId: 'topic_arrays',
    stem: 'For an array of length 3, what is the highest valid index?',
    page: 35,
    difficulty: 'beginner',
    correct: 'C',
    explanation: 'The highest index is length - 1, which is 2 (p.35).',
    options: [
      { label: 'A', text: '3', tag: PREC },
      { label: 'B', text: '4', tag: PREC },
      { label: 'C', text: '2', tag: null },
      { label: 'D', text: '1', tag: PREC },
    ],
  },
  {
    id: 'q_arrays_3',
    topicId: 'topic_arrays',
    stem: 'What does `pop` do?',
    page: 36,
    difficulty: 'beginner',
    correct: 'D',
    explanation: 'pop removes the last item and gives it back (p.36).',
    options: [
      { label: 'A', text: 'Adds an item to the end', tag: PREC },
      { label: 'B', text: 'Removes the first item', tag: PREC },
      { label: 'C', text: 'Empties the array', tag: TRUTHY },
      { label: 'D', text: 'Removes the last item and returns it', tag: null },
    ],
  },
  {
    id: 'q_objects_1',
    topicId: 'topic_objects',
    stem: "For `let student = { name: 'Ana', age: 16 };`, how do you read the name?",
    page: 39,
    difficulty: 'beginner',
    correct: 'A',
    explanation: 'Use a dot and the property name (p.39).',
    options: [
      { label: 'A', text: 'student.name', tag: null },
      { label: 'B', text: 'student[0]', tag: PREC },
      { label: 'C', text: 'student->name', tag: SLE },
      { label: 'D', text: 'name.student', tag: SCOPE },
    ],
  },
  {
    id: 'q_objects_2',
    topicId: 'topic_objects',
    stem: 'What happens with `student.grade = "A";` when `grade` does not exist yet?',
    page: 40,
    difficulty: 'intermediate',
    correct: 'B',
    explanation: 'Assigning to a property that does not exist adds it (p.40).',
    options: [
      { label: 'A', text: 'It causes an error', tag: SCOPE },
      { label: 'B', text: 'It adds the property', tag: null },
      { label: 'C', text: 'It compares grade with "A"', tag: AVC },
      { label: 'D', text: 'It replaces the whole object', tag: TRUTHY },
    ],
  },
  {
    id: 'q_objects_3',
    topicId: 'topic_objects',
    stem: 'When should you use an object rather than an array?',
    page: 42,
    difficulty: 'intermediate',
    correct: 'C',
    explanation:
      'Use an object when each value means something different and deserves a name (p.42).',
    options: [
      { label: 'A', text: 'When the items are in a strict order', tag: PREC },
      { label: 'B', text: 'When there are more than ten items', tag: TRUTHY },
      { label: 'C', text: 'When each value means something different', tag: null },
      { label: 'D', text: 'When the values are all numbers', tag: TRUTHY },
    ],
  },
];
